title: 'krish-iyer.github.io'
description: "dav1d and ARM assembly"
baseurl: "/"
url: "https://krish-iyer.github.io"

header_pages:
  - index.md
  - about.md
  - contact.md

cv_pdf: "/assets/Krishnan-Iyer-Resume.pdf"

style: light

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: krish-iyer/blog
plugins:
 - jekyll-seo-tag
